19 navbar
Leap1b-23-24/Team-5 pull request #22
Opened 2024-03-11 06:33 UTC by bekk1029

navbar mui icons

2024-03-11 06:36 UTC, Zorurunn requested changes

2024-03-11 06:36 UTC, Zorurunn commented on frontend/src/components/header/Search.tsx
ustgaarai

2024-03-11 06:36 UTC, Zorurunn commented on frontend/src/constants/index.ts
ustgaarai

2024-03-11 06:38 UTC, Zorurunn approved these changes

2024-03-11 06:40 UTC, ulaaka211 approved these changes
za yahudee

2024-03-11 06:44 UTC, Zorurunn approved these changes

2024-03-12 00:39 UTC, Zorurunn requested changes
navbar aa 2 branchaar push hiisen ymuu ?
ali neg branhchiig ni songood merge hiihgui bol 
main ruu navbar iig 2ynzaar zasaad merge hiih geheer conflict uuseh bh te 
2 branchiin ali zow be ?
hereggui pull reqyuestee ustagchihgui yu doo

2024-03-12 00:40 UTC, Zorurunn commented
aan ene nuguu conflict tei ni bn te eniigee ustagchihguiyu doo

2024-03-12 01:55 UTC, closed without merging